In [4]:
import numpy as np

In [5]:
# 2차원 array
gdp_array = np.array([
    [12257, 11561, 13165, 14673, 16496, 19403],  # 대한민국
    [39169, 34406, 32821, 35387, 38299, 37813],  # 일본
    [959, 1053, 1149, 1289, 1509, 1753],         # 중국
    [36335, 37133, 38023, 39496, 41713, 44115]   # 미국
])
gdp_array

array([[12257, 11561, 13165, 14673, 16496, 19403],
       [39169, 34406, 32821, 35387, 38299, 37813],
       [  959,  1053,  1149,  1289,  1509,  1753],
       [36335, 37133, 38023, 39496, 41713, 44115]])

In [6]:
# 일본
gdp_array[1]

array([39169, 34406, 32821, 35387, 38299, 37813])

In [7]:
# 일본, 2003
gdp_array[1][3]

np.int64(35387)

In [8]:
gdp_array[1, 3]

np.int64(35387)

In [9]:
# 일본,중국 , 2002-2004
gdp_array[1:3, 2:5]

array([[32821, 35387, 38299],
       [ 1149,  1289,  1509]])

In [10]:
# 모든 국가
gdp_array[:, 2:5]

array([[13165, 14673, 16496],
       [32821, 35387, 38299],
       [ 1149,  1289,  1509],
       [38023, 39496, 41713]])

In [11]:
# 모든 년도
gdp_array[1:3, :]

array([[39169, 34406, 32821, 35387, 38299, 37813],
       [  959,  1053,  1149,  1289,  1509,  1753]])

In [12]:
# 불린 인덱싱
gdp_array2 = np.array([6610, 7637, 8127, 8885, 10385, 12565, 13403, 12398, 8282, 10672])

In [13]:
gdp_array2 > 10000

array([False, False, False, False,  True,  True,  True,  True, False,
        True])

In [14]:
mask = gdp_array2 > 10000
gdp_array2[mask] # true인 인덱스만 받아옴

array([10385, 12565, 13403, 12398, 10672])

In [15]:
gdp_array2[gdp_array2 > 10000]

array([10385, 12565, 13403, 12398, 10672])

In [18]:
gdp_array2 > 10000

array([False, False, False, False,  True,  True,  True,  True, False,
        True])

In [19]:
gdp_array2 < 8000

array([ True,  True, False, False, False, False, False, False, False,
       False])

In [21]:
# or 연산
(gdp_array2 > 10000) | (gdp_array2 < 8000)

array([ True,  True, False, False,  True,  True,  True,  True, False,
        True])

In [22]:
gdp_array2[(gdp_array2 > 10000) | (gdp_array2 < 8000)]

array([ 6610,  7637, 10385, 12565, 13403, 12398, 10672])

In [23]:
# and
gdp_array2[(gdp_array2 <= 10000) & (gdp_array2 >= 8000)]

array([8127, 8885, 8282])

In [24]:
numbers_array = np.arange(1, 101)

In [25]:
# 짝수만
numbers_array[ numbers_array % 2 == 0]

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])