In [1]:
import numpy as np

In [2]:
array1 = np.array([1, 3, 5, 6, 7, 9])
array1

array([1, 3, 5, 6, 7, 9])

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(2, 10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(4, 17, 3)

array([ 4,  7, 10, 13, 16])

In [7]:
type(array1)

numpy.ndarray

In [9]:
array2 = np.array([[1,2,3,4], [5,6,7,8,], [9,10,11,12]])
array2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [10]:
array1.size

6

In [11]:
array2.size

12

In [12]:
array2.shape

(3, 4)

In [13]:
array1.shape

(6,)

In [14]:
gdp_array = np.array([6610, 7637, 8127, 8885, 10385, 12565, 13403, 12398, 8282, 10672])

In [15]:
gdp_array[0]

np.int64(6610)

In [16]:
gdp_array[2]

np.int64(8127)

In [17]:
print(gdp_array[2])

8127


In [18]:
gdp_array[[1, 3, 4]]

array([ 7637,  8885, 10385])

In [19]:
array3 = np.array([2, 1, 3, 5])
gdp_array[array3]

array([ 8127,  7637,  8885, 12565])

In [20]:
gdp_array[2:6]

array([ 8127,  8885, 10385, 12565])

In [21]:
gdp_array[:6]

array([ 6610,  7637,  8127,  8885, 10385, 12565])

In [22]:
gdp_array[5:]

array([12565, 13403, 12398,  8282, 10672])

In [23]:
gdp_array[1:8:3]

array([ 7637, 10385, 12398])