In [1]:
import numpy as np

In [7]:
# 2차원 array
gdp_array = np.array([
    [12257, 11561, 13165, 14673, 16496, 19403],  # 대한민국
    [39169, 34406, 32821, 35387, 38299, 37813],  # 일본
    [959, 1053, 1149, 1289, 1509, 1753],         # 중국
    [36335, 37133, 38023, 39496, 41713, 44115]   # 미국
])
gdp_array

array([[12257, 11561, 13165, 14673, 16496, 19403],
       [39169, 34406, 32821, 35387, 38299, 37813],
       [  959,  1053,  1149,  1289,  1509,  1753],
       [36335, 37133, 38023, 39496, 41713, 44115]])

In [3]:
# 일본
gdp_array[1]

array([39169, 34406, 32821, 35387, 38299, 37813])

In [5]:
# 일본, 2003
gdp_array[1][3]

np.int64(35387)

In [6]:
gdp_array[1, 3]

np.int64(35387)

In [9]:
# 일본,중국 , 2002-2004
gdp_array[1:3, 2:5]

array([[32821, 35387, 38299],
       [ 1149,  1289,  1509]])

In [10]:
# 모든 국가
gdp_array[:, 2:5]

array([[13165, 14673, 16496],
       [32821, 35387, 38299],
       [ 1149,  1289,  1509],
       [38023, 39496, 41713]])

In [11]:
# 모든 년도
gdp_array[1:3, :]

array([[39169, 34406, 32821, 35387, 38299, 37813],
       [  959,  1053,  1149,  1289,  1509,  1753]])

In [12]:
# 불린 인덱싱
gdp_array2 = np.array([6610, 7637, 8127, 8885, 10385, 12565, 13403, 12398, 8282, 10672])

In [13]:
gdp_array2 > 10000

array([False, False, False, False,  True,  True,  True,  True, False,
        True])

In [15]:
mask = gdp_array2 > 10000
gdp_array2[mask]

array([10385, 12565, 13403, 12398, 10672])