In [1]:
import numpy as np

In [2]:
# 기본 연산
gdp_korea_array = np.array([12257, 11561, 13165, 14673, 16496, 19403])

In [3]:
# 평균
gdp_korea_array.mean()

np.float64(14592.5)

In [4]:
# 힙계
gdp_korea_array.sum()

np.int64(87555)

In [5]:
# 최솟값
gdp_korea_array.min()

np.int64(11561)

In [7]:
# 최대값
gdp_korea_array.max()

np.int64(19403)

In [8]:
# 모든 인덱스에 1200 곱
gdp_korea_array * 1200

array([14708400, 13873200, 15798000, 17607600, 19795200, 23283600])

In [9]:
gdp_korea_array

array([12257, 11561, 13165, 14673, 16496, 19403])

In [10]:
gdp_korea_array = gdp_korea_array * 1200
gdp_korea_array

array([14708400, 13873200, 15798000, 17607600, 19795200, 23283600])

In [11]:
gdp_korea_array = gdp_korea_array / 1200
gdp_korea_array

array([12257., 11561., 13165., 14673., 16496., 19403.])

In [12]:
gdp_us_array = np.array([36335, 37133, 38023, 39496, 41713, 44115])

In [13]:
# array 두개 연산
gdp_us_array - gdp_korea_array

array([24078., 25572., 24858., 24823., 25217., 24712.])

In [14]:
gdp_us_array / gdp_korea_array

array([2.96442849, 3.21191938, 2.88818838, 2.69174675, 2.52867362,
       2.27361748])